name: "Build Python project" # build python project with uv

on:
  workflow_call:
    inputs:
      python_version:
        description: "Python version to use"
        required: true
        default: '3'
        type: string

jobs:
    # Install Python Dependency Job - Install the Python dependency using the `uv` tool. If the installation fails, the job will fail.
  install-python-dependency:
    uses: ./.github/workflows/install_python_dependency.yml

  build:
    needs: install-python-dependency
    runs-on: ubuntu-latest
    steps:
        # Build the project
        # Purpose: Build the project using the `uv` tool.
      - name: Build project
        run: |
          uv build    # run the build command

      - name : Validate the build
        run: |
          if [ -d "dist" ]; then
              echo "Build successful"
          else
              echo "Build failed"
              exit 1
          fi