name: "Build Python project" # build python project with uv

on:
  workflow_call:
    inputs:
      python_version:
        description: "Python version to use"
        required: true
        default: '3'
        type: string

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to .venv
        run: |
          $GITHUB_WORKSPACE/.venv/Scripts/activate.sh    
        # Build the project
        # Purpose: Build the project using the `uv` tool.
      - name: Build project
        run: |
          uv build    # run the build command

      - name : Validate the build
        run: |
          if [ -d "dist" ]; then
              echo "Build successful"
          else
              echo "Build failed"
              exit 1
          fi