name: Continuous Deployment Pipeline

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:

    DeployArtifact:
        uses: ./.github/workflows/build_artifact.yml
        with:
            image_name: 'artolepisa'
            registry_name: 'artolepisa'
