name: Install python dependency

on:
    workflow_call:


jobs:
    install-python-dependency:
        runs-on: ubuntu-latest
        steps:

          # Checkout the code
          # Purpose: Checkout the code from the repository.
          - name: Checkout Code
            uses: actions/checkout@v3
            with:
              fetch-depth: 0

                  # Check if Python is installed and exit if not
            # Purpose: Check if the specified Python versions are installed on the runner. If not, exit the workflow. note: The workflow will exit if any of the specified Python versions are not installed.
          - name: Check if Python is installed and exit if not
            run: |
                python_version=("3")
                for version in "${python_version[@]}"; do
                  if ! command -v python$version &> /dev/null; then
                    echo "Python $version could not be found"
                    exit 1
                  fi
                done
          # Install uv
          # Purpose: uv is a dependency manager and tool for managing Python projects.
          - name: Install uv
            run: pip install uv

          # Install dependencies and create virtual environment
          # Purpose: Install dependencies and create a virtual environment for the project.
          - name: Install dependencies and create virtual environment
            run: uv sync 
