name: Validate terraform code

on:
  pull_request:
    branches:
      - "**/terraform_**"
    paths:
      - "infrastructure/**"

jobs:
  commit-linter:
    uses: ./.github/workflows/workflow_commit_linter.yml
    with:
      node_version: "21.0"

  validate_terraform:
    needs: commit-linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: infrastructure/

      - name: Terraform Plan
        run: terraform plan
        working-directory: infrastructure/
