name: "Pull Request Pipeline"

on:
    pull_request:
        types: [opened, synchronize, reopened,closed]
        branches:
        - '**'
        paths-ignore:
        - "*.md"

jobs:
    # Initialize Environment Job - Initialize the environment for the PR pipeline. This job will run on the specified Linux distributions and execute the setup commands.

    initialize-linux-environment:
        uses: ./.github/workflows/initialize_linux_env.yml
        with:
            distros: '["ubuntu-22.04"]'
            commands: '["sudo apt update", "sudo apt install -y sudo", "sudo apt install -y git curl", "sudo curl -fsSL https://deb.nodesource.com/setup_21.x | sudo -E bash -", "sudo DEBIAN_FRONTEND=noninteractive apt install -y nodejs",  "sudo apt install -y python3-pip", "sudo apt install -y python3-venv", "sudo apt install -y python3"]'
            version_commands: '["git --version", "node --version", "npm --version", "npx commitlint --version", "python3 --version", "pip3 --version"]'

    # Commit Linter Job - Lint the commit messages in the PR and commits in the merge branch. If the commit messages do not follow the conventional commit message format, the job will fail.
    commit-linter:
        needs: initialize-linux-environment
        uses: ./.github/workflows/workflow_commit_linter.yml
        with:
            node_version: "21"

    # API Lint and Test Job - Lint the API code and run the tests. If the code does not pass the linting or tests, the job will fail.
    lint-test:
        needs: commit-linter
        uses: ./.github/workflows/lint_test.yml
        secrets: inherit
        with:
            python_version: '3'
       
    # Build Job - Build the Python project using the `uv` tool. If the build fails, the job will fail.
    build:
        needs: lint-test
        uses: ./.github/workflows/build.yml
        with:
            python_version: '3'

    
    # CodeQL Analysis Job - Analyze the code using CodeQL. If the code contains any security vulnerabilities, the job will fail.
    codeql-analysis:
        needs: build
        uses: ./.github/workflows/analysis.yml
        with:
            language: 'python'

