name: "Pull Request Pipeline"

on:
    pull_request:
        types: [opened, synchronize, reopened,closed]
        branches:
        - '**'
        paths-ignore:
        - "*.md"

env:
    COSMOS_ENDPOINT: ${{ secrets.COSMOS_ENDPOINT }}
    COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
jobs:
    # Commit Linter Job - Lint the commit messages in the PR and commits in the merge branch. If the commit messages do not follow the conventional commit message format, the job will fail.
    commit-linter:
        uses: ./.github/workflows/workflow_commit_linter.yml
        with:
            node_version: "21"

    # API Lint and Test Job - Lint the API code and run the tests. If the code does not pass the linting or tests, the job will fail.
    lint-test:
        needs: commit-linter
        uses: ./.github/workflows/lint_test.yml
        with:
            python_version: '3'
            cosmos_endpoint: ${{ github.env.COSMOS_ENDPOINT }}
            cosmos_key: ${{ github.env.COSMOS_KEY }}
    # Build Job - Build the Python project using the `uv` tool. If the build fails, the job will fail.
    build:
        needs: lint-test
        uses: ./.github/workflows/build.yml
        with:
            python_version: '3'

    
    # CodeQL Analysis Job - Analyze the code using CodeQL. If the code contains any security vulnerabilities, the job will fail.
    codeql-analysis:
        needs: build
        uses: ./.github/workflows/analysis.yml
        with:
            language: 'python'

